apiVersion: v1
kind: Service
metadata:
  name: easyshop-service
  namespace: easyshop
spec:
  type: NodePort
  selector:
    app: easyshop-deployment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      protocol: TCP 