apiVersion: v1
kind: Service
metadata:
  name: easyshop-service
  namespace: easyshop
  labels:
    app: easyshop-deployment
spec:
  type: NodePort
  selector:
    app: easyshop-deployment
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30001
